[build]
  command = "npm run build"

[build.environment]
  REACT_APP_GOOGLE_SHEET_ID = "${GOOGLE_SHEET_ID}"
  REACT_APP_GOOGLE_API_KEY = "${GOOGLE_API_KEY}"
  REACT_APP_BATTLEMETRICS_SERVER_ID = "${BATTLEMETRICS_SERVER_ID}"
  REACT_APP_BATTLEMETRICS_API_TOKEN = "${BATTLEMETRICS_API_TOKEN}"
